### ISSUE TITLE
Rules

### ISSUE THREAD

**Issue by maschmi** [Security-Card-Game/securityDeckGame#1]
Generell:
- Aktuell keine Traits und Rollen
- Aktuell kein echtes Spielziel, Hauptsache überleben
- Zu klären ob doppelte Oopsies zusammen geschlossen werden können (von der Engine nicht unterstützt), alternativ: Keine doppelten Oopsies.

Regelwerk:

1. Bestimme die Zusammenstellung
- 10 Event
- 5 Attack
- 15 Oopsies
- 5 Lucky

2. Multiplyer setzen
- x5
- resource gain = 10

3a. Play rounds - draw card
a) Oopsie -> ()
b) Event -> was immer auf der karte steht
c) Lucky -> was immer auf der karte steht
d) Attacke -> trifft oder trifft nicht, wenn trifft, dann resourcen entsprechen reduziren - auch wenn das Oopsie direkt geschlossen wird,  die Attacke bleibt bestehen, der Malus wird in der nächsten Runde neu bewertet (außer Spezialkarten behaupten was anderes)

3b. Play rounds - decide
Schließe ein Oopsie, setze Karten ein. Manche Karten können aktiv genutzt werden, manche haben einen Effekt der automatisch in Kraft tritt. Wenn das Oopsie nicht bezahlt werden kann, dann belibts offen und die Resourcen werden auf 0 gesetzt.

3c. Springe zu 3a wenn noch Karten da sind

-----------------

Game Engine:

- Karten werden zufällig aus dem Kartensatz gezogen (mit zurücklegen, Karten können doppelt gezogen werden)
- Multiplier wird größtenteils direkt angewendet, es gibt aber noch Bugs und Karten bei denen es noch nicht klappt
- Attacken Effekte müssen manuell eingestellt werden
- Attacken Dauer wird automatisch runtergezählt
- Effekte auf Fixkosten werden automatisch mit berücksichtig, für aktiv zu verwendende Karten (use button) nur dann, wenn sie aktiv sind (da gibt aber noch einen Bug)
- Schließen von Oopsies: Es wird automatisch gewürfelt, sollten nicht genug Resourcen vorhanden sein werden diese auf 0 gesetzt und das Oopsie bliebt offen.
- Manche Karten haben einen Use-Button
- Wenn keine Karten mehr verfügbar sind, dann endet das Spiel (Bug: Der aktuelle Spielstand verschwindet)

----------------

Große Zahlen erhöhen das gefühlte Risiko

**Comment by lisihocke** [comment]
@maschmi I just adapted the rules accordingly: https://github.com/Security-Card-Game/securityDeckGame/commit/9a5698f7c8bc5279ca18acb0747ba3d8111092ae Please check if anything is incorrect or missing, and whether we can close the issue.

**Comment by maschmi** [comment]
@lisihocke Thank you! This looks good. I just closed the "resources not available at games end" in the cli project. I think we should go over the known bugs once the other issues are closed in the cli project.
